version: '3'
services:
    mongodb:
        image: mongo
        ports:
            - "${MONGO_PORT}:27017"
        volumes:
            - /Users/wool/Dev/db_data_docker/mongodb:/data/db
        container_name: "docker-mongodb"
        env_file:
            - .env
